sudo: true
os: trusty
cache: false

env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz

before_install:
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core
- echo $TRAVIS_BRANCH
# exit 0

services:
  - docker

before_install:
    - docker pull ncino/ci-sfdx-lite
    - docker run -d -p 127.0.0.1:80:4567 ncino/ci-sfdx-lite /bin/sh -c "cd /root/ci-sfdx-lite; bundle exec foreman start;"
    - docker ps -a
    - sfdx -v
    #- docker run ncino/ci-sfdx-lite /bin/sh -c "cd /root/ci-sfdx-lite; bundle exec rake test"

script: sfdx -v
    #bash ./deploy.sh $TRAVIS_BRANCH 

   #  on: 
    #   branch: develop
  # deploy master to production
  #- provider: script
   # script: bash scripts/deploy.sh production
   # on:
   #   branch: master
