sudo: true
os: trusty
cache: false

env:
#- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz

before_install:
#- export SFDX_AUTOUPDATE_DISABLE=false
#- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
#- export SFDX_DOMAIN_RETRY=300
#- export SFDX_DISABLE_APP_HUB=true
#- export SFDX_LOG_LEVEL=DEBUG
#- mkdir sfdx
#- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
#- "./sfdx/install"
#- export PATH=./sfdx/$(pwd):$PATH
#- sfdx --version
#- sfdx plugins --core
#- echo $TRAVIS_BRANCH

#- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key --username $USERNAME --setdefaultdevhubusername -a SandBox1_Hub
#	sfdx force:mdapi:deploy -d mdapi_output/ -u HubOrg -w 5

#- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key --username $USERNAME --setdefaultdevhubusername -a SandBox2_Hub
#	sfdx force:mdapi:deploy -d mdapi_output/ -u HubOrg -w 5
#	exit 0



script: bash ./deploy.sh $TRAVIS_BRANCH 
   #  on: 
    #   branch: develop
  # deploy master to production
  #- provider: script
   # script: bash scripts/deploy.sh production
   # on:
   #   branch: master

